version: "3.3"
services:
  web:
    image: h20180061/dashboard:${WEB_TAG}
    environment: 
      - TIME_ZONE=Asia/Kolkata
    ports:
      - "80:80"
    container_name: web
    depends_on:
      - app
    networks:
        - network1
  app:
    image: h20180061/trends:${APP_TAG}
    environment: 
      - TIME_ZONE=Asia/Kolkata
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - /d/wsl/data/trends:/home/app/data
    networks:
        - network1
 

networks:
  network1: